"""add sent_alerts table

Revision ID: 3dc42d0b2f1a
Revises: c930fca3442e
Create Date: 2026-06-12 14:43:18.652124

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '3dc42d0b2f1a'
down_revision: str | None = 'c930fca3442e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sent_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'listing_id', name='uq_sent_alert')
    )
    op.create_index(op.f('ix_sent_alerts_listing_id'), 'sent_alerts', ['listing_id'], unique=False)
    op.create_index(op.f('ix_sent_alerts_user_id'), 'sent_alerts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sent_alerts_user_id'), table_name='sent_alerts')
    op.drop_index(op.f('ix_sent_alerts_listing_id'), table_name='sent_alerts')
    op.drop_table('sent_alerts')
    # ### end Alembic commands ###
