"""initial schema

Revision ID: c930fca3442e
Revises: 
Create Date: 2026-06-12 14:27:20.062937

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'c930fca3442e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_chat_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_chat_id'), 'users', ['telegram_chat_id'], unique=True)
    op.create_table('watch_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('reference_number', sa.String(length=50), nullable=False),
    sa.Column('estimated_market_value', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watch_references_brand'), 'watch_references', ['brand'], unique=False)
    op.create_index(op.f('ix_watch_references_reference_number'), 'watch_references', ['reference_number'], unique=True)
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('condition', sa.Enum('new', 'used', name='conditionenum'), nullable=False),
    sa.Column('has_box_papers', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('active', 'sold', name='listingstatusenum'), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['reference_id'], ['watch_references.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_listings_reference_id'), 'listings', ['reference_id'], unique=False)
    op.create_index(op.f('ix_listings_status'), 'listings', ['status'], unique=False)
    op.create_table('user_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('max_price', sa.Float(), nullable=True),
    sa.Column('min_margin_percentage', sa.Float(), nullable=False),
    sa.Column('target_brand', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_filters_user_id'), 'user_filters', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_filters_user_id'), table_name='user_filters')
    op.drop_table('user_filters')
    op.drop_index(op.f('ix_listings_status'), table_name='listings')
    op.drop_index(op.f('ix_listings_reference_id'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_watch_references_reference_number'), table_name='watch_references')
    op.drop_index(op.f('ix_watch_references_brand'), table_name='watch_references')
    op.drop_table('watch_references')
    op.drop_index(op.f('ix_users_telegram_chat_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
